services:
  - type: web
    name: maurmaket
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MCC_KEY
        sync: false
      - key: MCC_WEBHOOK_SECRET
        sync: false
      - key: MONCASH_PAY_CREATE_URL
        sync: false
      - key: PORT
        value: 3001
    healthCheckPath: /api/health
    autoDeploy: true
