/**
 * JSON Translation Provider
 *
 * Loads per-language JSON files (Paraglide message format).
 * This is the current/legacy engine — runtime lookup with
 * English fallback.
 */
import type { Language, TranslationProvider } from '../types';

// Per-language message dictionaries (generated by extract-i18n.cjs)
import enMessages from '../../../messages/en.json';
import htMessages from '../../../messages/ht.json';
import frMessages from '../../../messages/fr.json';

const messages: Record<Language, Record<string, string>> = {
  en: enMessages,
  ht: htMessages,
  fr: frMessages,
};

export const jsonProvider: TranslationProvider = {
  lookup(key: string, lang: Language): string | undefined {
    // Try current language, fall back to English
    return messages[lang]?.[key] ?? messages.en[key];
  },
};
