
// Auto-generated by i18n-runtime-validate.cjs — minimal RN seam for Node tests
const backends = require('./rn-stub-backends.cjs');
module.exports = {
  Platform: { OS: backends.currentOS, select: (o) => o[backends.currentOS] ?? o.default },
  AsyncStorage: null,
  NativeModules: {},
  TurboModuleRegistry: { getEnforcing: () => ({}), get: () => ({}) },
};
